:concurrency: 3
:timeout: 60
:verbose: true

:scheduler:
  :schedule:
    abandoned_carts_cleanup:
      cron: "*/15 * * * *"
      class: "Carts::AbandonedCleanupJob"

:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
